apiVersion: v1
kind: Secret
metadata:
  name: main-secret
  namespace: naa-app
type: Opaque
stringData:
  SERVER_SECRET : <SAME STRING USED IN auth-secret>
  AUTH_SERVER_URL : http://auth-service:5000/
  AUTH_SERVER_REDIRECT_URL : /auth/

  # Nutrition API
  SPOONACULAR_BASE_URL : https://api.spoonacular.com/
  SPOONACULAR_API_KEY : <GET FROM SPOONACULAR API>

  # IBM
  DB2_URL : <databasename>;HOSTNAME=<your-hostname>;PORT=<portnumber>;SECURITY=SSL;UID=<username>;PWD=<password>

  COS_ENDPOINT : https://s3.jp-tok.cloud-object-storage.appdomain.cloud
  COS_INSTANCE_CRN : '<GET FROM IBM COS>'
  COS_API_KEY_ID : <GET FROM IBM COS>
