apiVersion: v1
kind: Service
metadata:
  name: flask-service
  labels:
    app: flask-app
spec:
  type: LoadBalancer 
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: flask-app